apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /pdf
      route:
        - destination:
            host: pdf-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /image
      route:
        - destination:
            host: image-service
            port:
              number: 80
